---
dist: xenial
language: python
python: 3.7
services: docker
install:
- git clone https://github.com/systemslab/popper /tmp/popper
- git -C /tmp/popper checkout v2.4.2
- export PYTHONUNBUFFERED=1
- pip install /tmp/popper/cli
script: popper run
